#pragma once

#ifndef FLOW_UI_DEV_MODE
#define FLOW_UI_DEV_MODE 1
#endif

#ifndef FLOW_UI_DEV_CAPTURE_CLAY
#define FLOW_UI_DEV_CAPTURE_CLAY 1
#endif

#ifndef FLOW_UI_HAS_BAKED_CHANGES
#define FLOW_UI_HAS_BAKED_CHANGES 1
#endif

#ifndef FLOWUI_BAKE_BUILD_FINGERPRINT
#define FLOWUI_BAKE_BUILD_FINGERPRINT "FlowUi-0.1.0"
#endif

#ifndef FLOWUI_DEV_TIMING_LEVEL
#define FLOWUI_DEV_TIMING_LEVEL 2
#endif

#ifndef FLOWUI_DEV_MEMORY_LEVEL
#define FLOWUI_DEV_MEMORY_LEVEL 2
#endif

#ifndef FLOWUI_DEV_ERROR_LEVEL
#define FLOWUI_DEV_ERROR_LEVEL 2
#endif

#ifndef COMPILE_FSELI
#define COMPILE_FSELI 1
#endif

#define FLOWUI_PUBLIC_VULKAN_INTEROP 1
#define FLOWUI_INCLUDE_ICON_MANAGER 1
