#pragma once

#include <cstddef>
#include <cstdint>
#include <limits>
#include <string>
#include <string_view>
#include <unordered_map>
#include <vector>

#include <clay.h>

#include "FlowUi/PublicStructs.hpp"
#include "window/Inputs.hpp"

struct FontManager;

namespace FlowUi {

/** @addtogroup flowui_input_field_manager
 * @{
 */

/** @brief Rectangle override emitted for input selection/caret rendering. */
struct InputFieldRectOverride {
	/** @brief Render command index before which the rectangle should be inserted. */
	int32_t insertBeforeCommandIndex = 0;
	/** @brief Rectangle bounds. */
	Clay_BoundingBox boundingBox{};
	/** @brief Rectangle color. */
	Clay_Color color = Clay_Color{0.0f, 0.0f, 0.0f, 0.0f};
};

/** @brief Byte range whose text color should be overridden. */
struct InputFieldTextColorRangeOverride {
	/** @brief Start byte offset. */
	size_t startByteOffset = 0u;
	/** @brief End byte offset. */
	size_t endByteOffset = 0u;
};

/** @brief Text color override for an existing text render command. */
struct InputFieldTextColorOverride {
	/** @brief Render command index to modify. */
	int32_t commandIndex = 0;
	/** @brief Replacement text color. */
	Clay_Color color = Clay_Color{0.0f, 0.0f, 0.0f, 0.0f};
	/** @brief Byte ranges affected by the override. */
	std::vector<InputFieldTextColorRangeOverride> ranges{};
};

/** @brief Per-frame render overrides generated by input fields. */
struct InputFieldFrameOverrides {
	/** @brief Selection/caret rectangles to insert. */
	std::vector<InputFieldRectOverride> rects{};
	/** @brief Text color ranges to apply. */
	std::vector<InputFieldTextColorOverride> textColorOverrides{};
};

/** @brief Manages text input fields, focus, caret state, and edit operations. */
class InputFieldManager {
public:
	/** @brief Requested caret operation for an input field. */
	enum class CaretRequestKind : uint8_t {
		SetPrimary = 0,
		Add = 1,
		ClearAll = 2,
	};

	/** @brief Configuration for a requested input field. */
	struct FieldConfig {
		/** @brief Whether the field accepts edits. */
		bool readOnly = false;
		/** @brief Whether newline input is allowed. */
		bool allowNewline = false;
		/** @brief Whether arrow keys navigate inside the field. */
		bool allowArrowNavigation = true;
		/** @brief Maximum text byte count. */
		size_t maxBytes = std::numeric_limits<size_t>::max();
	};

	/** @brief Input field request submitted by UI code. */
	struct FieldRequest {
		/** @brief Stable field id. */
		std::string_view fieldId{};
		/** @brief Initial text used when the field state is first created. */
		std::string_view initialText{};
		/** @brief Field behavior configuration. */
		FieldConfig config{};
		/** @brief Clay text element id for measuring/caret placement. */
		Clay_ElementId textElementId{};
		/** @brief Clay content element id for pointer hit testing. */
		Clay_ElementId contentElementId{};
	};

	/** @brief Result returned from an input field request. */
	struct FieldQueryResult {
		/** @brief Current text for the field. */
		std::string_view text{};
		/** @brief Whether this field owns the primary caret. */
		bool hasPrimaryCaret = false;
		/** @brief Whether this field has a selection. */
		bool hasSelection = false;
	};

	/** @brief Apply input field rendering configuration. */
	void setConfig(const InputManagerConfig& config);
	/** @brief Set font manager used for text measurement. */
	void setFontManager(const ::FontManager* fontManager, float pointsToPixelsScale);
	/** @brief Begin input field processing for a frame. */
	void beginFrame(const FrameInput& currentInput, const FrameInput& previousInput);
	/** @brief End input field processing and return adjusted render commands. */
	Clay_RenderCommandArray endFrame(const Clay_RenderCommandArray& renderCommands);
	/** @brief Return render overrides produced this frame. */
	const InputFieldFrameOverrides& frameOverrides() const { return frameOverrides_; }
	/** @brief Register/update an input field for the current frame. */
	FieldQueryResult requestField(const FieldRequest& request);
	/** @brief Request focus/caret changes for a field. */
	void requestCaret(std::string_view fieldId, CaretRequestKind kind);
	/** @brief Remove a field by id. */
	bool removeField(std::string_view fieldId);
	/** @brief Clear all managed field state. */
	void clear();
	/** @brief Return true if any field owns primary focus. */
	bool hasPrimaryFieldFocus() const;
	/** @brief Return the current selected text. */
	std::string_view getSelectedText() const;
	/** @brief Insert UTF-8 text at the primary caret. */
	bool insertTextAtPrimaryCaret(std::string_view utf8Text);

private:
	struct CaretState {
		size_t anchorByteOffset = 0u;
		size_t headByteOffset = 0u;
	};

	struct FieldState {
		std::string text{};
		FieldConfig config{};
		std::vector<CaretState> carets{};
		Clay_ElementId textElementId{};
		Clay_ElementId contentElementId{};
		bool touchedThisFrame = false;
	};

	struct SelectionRange {
		size_t start = 0u;
		size_t end = 0u;
	};

	struct KeyRepeatState {
		bool wasDown = false;
		double repeatCountdownSeconds = 0.0;
	};

	struct PointerDragState {
		bool active = false;
		std::string fieldId{};
		size_t anchorByteOffset = 0u;
	};

	void applyKeyboardEdits();
	void markCaretBlinkReset();
	void updateCaretBlinkVisibility(bool hasAnyActiveCaret);
	bool shouldTriggerActionWithRepeat(int key, KeyRepeatState& state);
	void applyTextInsertion(FieldState& field, std::string_view utf8Text);
	void applyDelete(FieldState& field, bool backspace);
	void moveCaretsHorizontal(FieldState& field, int direction, bool selecting);
	void clampCaretsToText(FieldState& field) const;
	void eraseRange(FieldState& field, size_t start, size_t end, size_t sourceCaretIndex);

	static size_t clampUtf8Boundary(std::string_view text, size_t offset);
	static size_t nextUtf8Codepoint(std::string_view text, size_t offset);
	static size_t prevUtf8Codepoint(std::string_view text, size_t offset);
	static bool isUtf8ContinuationByte(char c);
	static bool keyPressedThisFrame(const FrameInput& currentInput, const FrameInput& previousInput, int key);
	static bool keyDown(const FrameInput& input, int key);
	static bool caretHasSelection(const CaretState& caret);
	static size_t caretSelectionStart(const CaretState& caret);
	static size_t caretSelectionEnd(const CaretState& caret);
	static std::string encodeTextInput(const FrameInput& input, bool allowNewline);
	static bool elementIdIsValid(const Clay_ElementId& id);

	float measureTextSlice(const Clay_StringSlice& text, const Clay_TextRenderData& textData) const;
	static Clay_StringSlice subSlice(const Clay_StringSlice& source, int start, int length);
	static bool findSliceOffsetFromCursor(
		std::string_view fullText,
		std::string_view needle,
		size_t cursor,
		size_t& outOffset);
	std::vector<SelectionRange> mergedSelectionRanges(const FieldState& field) const;

private:
	FrameInput currentInput_{};
	FrameInput previousInput_{};
	std::unordered_map<std::string, FieldState> fieldsById_{};
	std::string primaryFieldId_{};
	InputManagerConfig config_{};
	const ::FontManager* fontManager_ = nullptr;
	float pointsToPixelsScale_ = 96.0f / 72.0f;
	KeyRepeatState leftKeyRepeat_{};
	KeyRepeatState rightKeyRepeat_{};
	KeyRepeatState backspaceKeyRepeat_{};
	KeyRepeatState deleteKeyRepeat_{};
	PointerDragState pointerDrag_{};
	double caretBlinkElapsedSeconds_ = 0.0;
	bool caretBlinkResetPending_ = true;
	bool emitCaretsThisFrame_ = true;
	InputFieldFrameOverrides frameOverrides_{};
};

/** @} */

} // namespace FlowUi
