#include "CppCodeGenerator.hpp"

#include <algorithm>
#include <array>
#include <fstream>
#include <iomanip>
#include <map>
#include <set>
#include <sstream>
#include <string_view>

namespace flowui::bake_tool {
namespace {

std::string hexLiteral(std::uint64_t value) {
	std::ostringstream output;
	output << "0x" << std::uppercase << std::hex << value << "ull";
	return output.str();
}

std::string escaped(std::string_view value) {
	std::string output;
	for (const char character : value) {
		switch (character) {
		case '\\': output += "\\\\"; break;
		case '"': output += "\\\""; break;
		case '\n': output += "\\n"; break;
		case '\r': output += "\\r"; break;
		case '\t': output += "\\t"; break;
		default: output += character;
		}
	}
	return output;
}

bool writeIfChanged(const std::filesystem::path& path, const std::string& contents, std::string& error) {
	{
		std::ifstream existing(path, std::ios::binary);
		if (existing) {
			const std::string old((std::istreambuf_iterator<char>(existing)), {});
			if (old == contents) {
				std::error_code touchError;
				std::filesystem::last_write_time(
					path, std::filesystem::file_time_type::clock::now(), touchError);
				if (touchError) { error = "cannot update generated file timestamp: " + path.string(); return false; }
				return true;
			}
		}
	}
	std::ofstream output(path, std::ios::binary | std::ios::trunc);
	if (!output) { error = "cannot write generated file: " + path.string(); return false; }
	output.write(contents.data(), static_cast<std::streamsize>(contents.size()));
	if (!output) { error = "failed while writing generated file: " + path.string(); return false; }
	return true;
}

struct ElementGroup {
	std::string owner;
	std::vector<const Entry*> definitions;
	std::map<std::uint64_t, std::vector<const Entry*>> instances;
};

struct ThemeVariantGroup {
	std::string owner;
	std::map<std::string, std::vector<const Entry*>> variants;
};

void emitAssignments(std::ostringstream& output, const std::vector<const Entry*>& entries, std::string_view indent) {
	for (const Entry* entry : entries) {
		output << indent << "p." << entry->fieldPath << " = " << entry->cppValue << ";\n";
	}
}

} // namespace

bool generateCpp(
	const Manifest& manifest,
	const std::filesystem::path& outputDirectory,
	std::string& error) {
	std::map<std::uint64_t, ElementGroup> elements;
	std::map<std::uint64_t, ThemeVariantGroup> themes;
	std::set<std::string> headers;
	for (const Entry& entry : manifest.entries) {
		headers.insert(entry.sourceHeader);
		if (entry.targetKind == TargetKind::Element) {
			auto& group = elements[entry.definitionId];
			if (!group.owner.empty() && group.owner != entry.ownerCppType) { error = "one definitionId maps to multiple parameter C++ types"; return false; }
			group.owner = entry.ownerCppType;
			if (entry.targetScope == TargetScope::Definition) group.definitions.push_back(&entry);
			else group.instances[entry.instanceKey].push_back(&entry);
		} else {
			auto& group = themes[entry.themeType];
			if (!group.owner.empty() && group.owner != entry.ownerCppType) { error = "one themeType maps to multiple C++ types"; return false; }
			group.owner = entry.ownerCppType;
			group.variants[entry.themeVariant].push_back(&entry);
		}
	}

	std::ostringstream header;
	header << "// Auto-generated by flowui-dev-generate. DO NOT EDIT.\n"
		"#pragma once\n\n"
		"#include <cstdint>\n#include <string_view>\n"
		"#include \"FlowUi/ElementID.hpp\"\n"
		"#include \"internal/ElementInstanceKey.hpp\"\n\n"
		"namespace FlowUi::baked {\n\n"
		"inline constexpr std::uint64_t schemaFingerprint = " << hexLiteral(manifest.schemaFingerprint) << ";\n\n"
		"[[nodiscard]] constexpr bool hasBakedDefinitionChanges(FlowDefinitionID definition) noexcept {\n"
		"\tswitch (definition.value) {\n";
	for (const auto& [id, group] : elements) if (!group.definitions.empty())
		header << "\tcase " << hexLiteral(id) << ": return true;\n";
	header << "\tdefault: return false;\n\t}\n}\n\n"
		"[[nodiscard]] constexpr bool hasBakedInstanceChanges(FlowDefinitionID definition) noexcept {\n"
		"\tswitch (definition.value) {\n";
	for (const auto& [id, group] : elements) if (!group.instances.empty())
		header << "\tcase " << hexLiteral(id) << ": return true;\n";
	header << "\tdefault: return false;\n\t}\n}\n\n"
		"[[nodiscard]] constexpr bool hasBakedThemeChanges(std::uint64_t themeType) noexcept {\n"
		"\tswitch (themeType) {\n";
	for (const auto& [type, group] : themes) if (!group.variants.empty())
		header << "\tcase " << hexLiteral(type) << ": return true;\n";
	header << "\tdefault: return false;\n\t}\n}\n\n"
		"void applyBakedParametersErased(FlowDefinitionID definition,\n"
		"\tdetail::element::ElementInstanceKey instance, void* parametersDraft) noexcept;\n"
		"void applyBakedThemeErased(std::uint64_t themeType, std::string_view variant,\n"
		"\tvoid* themeDraft) noexcept;\n\n"
		"} // namespace FlowUi::baked\n";

	std::ostringstream source;
	source << "// Auto-generated by flowui-dev-generate. DO NOT EDIT.\n"
		"#include \"FlowUiBakedChanges.hpp\"\n\n"
		"#include <algorithm>\n#include <array>\n#include <cstddef>\n\n";
	for (const auto& include : headers) source << "#include \"" << escaped(include) << "\"\n";
	source << "\nnamespace FlowUi::baked {\nnamespace {\n\n";
	for (const auto& [id, group] : elements) {
		source << "void applyElement_" << std::hex << id << std::dec << "(" << group.owner
			<< "& p, detail::element::ElementInstanceKey key) noexcept {\n";
		emitAssignments(source, group.definitions, "\t");
		if (group.instances.size() <= 7) {
			if (!group.instances.empty()) source << "\tswitch (key.value) {\n";
			for (const auto& [key, entries] : group.instances) {
				source << "\tcase " << hexLiteral(key) << ":\n";
				emitAssignments(source, entries, "\t\t");
				source << "\t\tbreak;\n";
			}
			if (!group.instances.empty()) source << "\tdefault: break;\n\t}\n";
		} else {
			source << "\tstatic constexpr std::array<std::uint64_t, " << group.instances.size() << "> keys{\n";
			for (const auto& [key, ignored] : group.instances) { (void)ignored; source << "\t\t" << hexLiteral(key) << ",\n"; }
			source << "\t};\n\tconst auto found = std::lower_bound(keys.begin(), keys.end(), key.value);\n"
				"\tif (found == keys.end() || *found != key.value) return;\n"
				"\tswitch (static_cast<std::size_t>(found - keys.begin())) {\n";
			std::size_t index = 0;
			for (const auto& [ignored, entries] : group.instances) {
				(void)ignored; source << "\tcase " << index++ << ":\n"; emitAssignments(source, entries, "\t\t"); source << "\t\tbreak;\n";
			}
			source << "\tdefault: break;\n\t}\n";
		}
		source << "}\n\n";
	}
	source << "} // namespace\n\n"
		"void applyBakedParametersErased(FlowDefinitionID definition,\n"
		"\tdetail::element::ElementInstanceKey instance, void* parametersDraft) noexcept {\n"
		"\tif (!parametersDraft) return;\n\tswitch (definition.value) {\n";
	for (const auto& [id, group] : elements) {
		source << "\tcase " << hexLiteral(id) << ": applyElement_" << std::hex << id << std::dec
			<< "(*static_cast<" << group.owner << "*>(parametersDraft), instance); break;\n";
	}
	source << "\tdefault: break;\n\t}\n}\n\n"
		"void applyBakedThemeErased(std::uint64_t themeType, std::string_view variant,\n"
		"\tvoid* themeDraft) noexcept {\n\tif (!themeDraft) return;\n\tswitch (themeType) {\n";
	for (const auto& [type, group] : themes) {
		source << "\tcase " << hexLiteral(type) << ": {\n\t\tauto& p = *static_cast<" << group.owner << "*>(themeDraft);\n";
		for (const auto& [variant, entries] : group.variants) {
			source << "\t\tif (variant == \"" << escaped(variant) << "\") {\n";
			emitAssignments(source, entries, "\t\t\t");
			source << "\t\t\treturn;\n\t\t}\n";
		}
		source << "\t\tbreak;\n\t}\n";
	}
	source << "\tdefault: break;\n\t}\n}\n\n} // namespace FlowUi::baked\n";

	std::error_code filesystemError;
	std::filesystem::create_directories(outputDirectory, filesystemError);
	if (filesystemError) { error = "cannot create output directory: " + filesystemError.message(); return false; }
	return writeIfChanged(outputDirectory / "FlowUiBakedChanges.hpp", header.str(), error) &&
		writeIfChanged(outputDirectory / "FlowUiBakedChanges.cpp", source.str(), error);
}

} // namespace flowui::bake_tool
