// Auto-generated by flowui-dev-generate. DO NOT EDIT.
#include "FlowUiBakedChanges.hpp"

#include <algorithm>
#include <array>
#include <cstddef>


namespace FlowUi::baked {
namespace {

} // namespace

void applyBakedParametersErased(FlowDefinitionID definition,
	detail::element::ElementInstanceKey instance, void* parametersDraft) noexcept {
	if (!parametersDraft) return;
	switch (definition.value) {
	default: break;
	}
}

void applyBakedThemeErased(std::uint64_t themeType, std::string_view variant,
	void* themeDraft) noexcept {
	if (!themeDraft) return;
	switch (themeType) {
	default: break;
	}
}

} // namespace FlowUi::baked
