// Auto-generated by flowui-dev-generate. DO NOT EDIT.
#pragma once

#include <cstdint>
#include <string_view>
#include "FlowUi/ElementID.hpp"
#include "internal/ElementInstanceKey.hpp"

namespace FlowUi::baked {

inline constexpr std::uint64_t schemaFingerprint = 0x0ull;

[[nodiscard]] constexpr bool hasBakedDefinitionChanges(FlowDefinitionID definition) noexcept {
	switch (definition.value) {
	default: return false;
	}
}

[[nodiscard]] constexpr bool hasBakedInstanceChanges(FlowDefinitionID definition) noexcept {
	switch (definition.value) {
	default: return false;
	}
}

[[nodiscard]] constexpr bool hasBakedThemeChanges(std::uint64_t themeType) noexcept {
	switch (themeType) {
	default: return false;
	}
}

void applyBakedParametersErased(FlowDefinitionID definition,
	detail::element::ElementInstanceKey instance, void* parametersDraft) noexcept;
void applyBakedThemeErased(std::uint64_t themeType, std::string_view variant,
	void* themeDraft) noexcept;

} // namespace FlowUi::baked
