#pragma once

#include <cstdint>
#include <filesystem>
#include <string>
#include <unordered_map>
#include <vector>

#include <vulkan/vulkan.h>

#include "managers/structs/FontManagerStructs.hpp"

struct VmaAllocation_T;

namespace FlowUi::Font {

/** @addtogroup flowui_font_resources
 * @{
 */

/**
 * @brief Baked glyph metrics and atlas coordinates.
 *
 * GlyphData is loaded from baked font data or generated by runtime font baking.
 * It is consumed by FlowUi text layout and rendering code.
 */
struct GlyphData {
	/** @brief Unicode codepoint represented by the glyph. */
	uint32_t codepoint = 0;
	/** @brief Source atlas image index. */
	uint32_t sourceImageIndex = 0;
	/** @brief Left glyph plane bound in font design space. */
	float planeLeft = 0.0f;
	/** @brief Bottom glyph plane bound in font design space. */
	float planeBottom = 0.0f;
	/** @brief Right glyph plane bound in font design space. */
	float planeRight = 0.0f;
	/** @brief Top glyph plane bound in font design space. */
	float planeTop = 0.0f;
	/** @brief Left glyph atlas bound in source atlas pixels. */
	float imageLeft = 0.0f;
	/** @brief Bottom glyph atlas bound in source atlas pixels. */
	float imageBottom = 0.0f;
	/** @brief Right glyph atlas bound in source atlas pixels. */
	float imageRight = 0.0f;
	/** @brief Top glyph atlas bound in source atlas pixels. */
	float imageTop = 0.0f;
	/** @brief Horizontal glyph advance. */
	float advanceX = 0.0f;
	/** @brief Vertical glyph advance. */
	float advanceY = 0.0f;
};

/**
 * @brief One baked variant of a font face.
 *
 * A variant stores metrics, glyphs, and kerning for one loaded font face
 * variant. FontFaceData selects one variant as the default for layout.
 */
struct FontVariantData {
	/** @brief Source font variant flags from the loaded font data. */
	uint32_t flags = 0;
	/** @brief Font weight. */
	uint32_t weight = 0;
	/** @brief Glyph index used as fallback. */
	uint32_t fallbackGlyphIndex = 0;
	/** @brief Baked font size in pixels. */
	float fontSizePx = 0.0f;
	/** @brief MSDF distance range. */
	float distanceRange = 0.0f;
	/** @brief EM size from font metadata. */
	float emSize = 0.0f;
	/** @brief Font ascender metric. */
	float ascender = 0.0f;
	/** @brief Font descender metric. */
	float descender = 0.0f;
	/** @brief Font line height metric. */
	float lineHeight = 0.0f;
	/** @brief Underline Y metric. */
	float underlineY = 0.0f;
	/** @brief Underline thickness metric. */
	float underlineThickness = 0.0f;
	/** @brief MSDF distance range midpoint. */
	float distanceRangeMiddle = 0.0f;
	/** @brief Variant name. */
	std::string name;
	/** @brief Raw metadata associated with the variant. */
	std::string metadata;
	/** @brief Glyph table. */
	std::vector<GlyphData> glyphs;
	/** @brief Unicode codepoint to glyph index lookup. */
	std::unordered_map<uint32_t, uint32_t> unicodeToGlyphIndex;
	/** @brief Kerning pair lookup table. */
	std::unordered_map<uint64_t, float> kerningPairs;

	/** @brief Pack two codepoints into the kerning lookup key. */
	static uint64_t kerningKey(uint32_t leftCodepoint, uint32_t rightCodepoint) {
		return (static_cast<uint64_t>(leftCodepoint) << 32u) | static_cast<uint64_t>(rightCodepoint);
	}

	/** @brief Return kerning advance for a codepoint pair. */
	float kerningAdvance(uint32_t leftCodepoint, uint32_t rightCodepoint) const {
		const auto it = kerningPairs.find(kerningKey(leftCodepoint, rightCodepoint));
		return (it != kerningPairs.end()) ? it->second : 0.0f;
	}
};

/**
 * @brief Loaded font face and its baked variants.
 *
 * FontFaceData is returned by FlowUi::FontManager::getFontById() for applications that
 * need direct access to loaded font metrics or atlas placement data.
 */
struct FontFaceData {
	/** @brief FlowUi font id. */
	FontId id = 0;
	/** @brief Font face name. */
	std::string name;
	/** @brief Source file path. */
	std::filesystem::path sourcePath;
	/** @brief Atlas layer used by this font face. */
	uint32_t atlasLayer = 0;
	/** @brief Atlas width in pixels. */
	uint32_t atlasWidth = 0;
	/** @brief Atlas height in pixels. */
	uint32_t atlasHeight = 0;
	/** @brief X offset where this face's source atlas was placed inside the atlas page. */
	uint32_t sourceAtlasX = 0;
	/** @brief Y offset where this face's source atlas was placed inside the atlas page. */
	uint32_t sourceAtlasY = 0;
	/** @brief Source atlas width before placement into the atlas page. */
	uint32_t sourceAtlasWidth = 0;
	/** @brief Source atlas height before placement into the atlas page. */
	uint32_t sourceAtlasHeight = 0;
	/** @brief Source atlas image type from the loaded font data. */
	uint32_t imageType = 0;
	/** @brief Raw metadata associated with the face. */
	std::string metadata;
	/** @brief Default variant index. */
	uint32_t defaultVariantIndex = 0;
	/** @brief Baked variants for this face. */
	std::vector<FontVariantData> variants;

	/** @brief Return the default variant, or nullptr if unavailable. */
	const FontVariantData* defaultVariant() const {
		if (variants.empty() || defaultVariantIndex >= variants.size()) {
			return nullptr;
		}
		return &variants[defaultVariantIndex];
	}
};

/**
 * @brief Vulkan resources for the font atlas array.
 *
 * AtlasArrayResource is returned by FlowUi::FontManager::getAtlasResource() for
 * renderer integrations that need to bind FlowUi's font atlas directly.
 */
struct AtlasArrayResource {
	/** @brief Vulkan image handle. */
	VkImage image = VK_NULL_HANDLE;
	/** @brief VMA allocation handle. */
	VmaAllocation_T* allocation = nullptr;
	/** @brief Vulkan image view handle. */
	VkImageView view = VK_NULL_HANDLE;
	/** @brief Vulkan sampler handle. */
	VkSampler sampler = VK_NULL_HANDLE;
	/** @brief Atlas width in pixels. */
	uint32_t width = 0;
	/** @brief Atlas height in pixels. */
	uint32_t height = 0;
	/** @brief Number of atlas layers currently used. */
	uint32_t layersUsed = 0;
	/** @brief Number of atlas layers currently allocated. */
	uint32_t layersCapacity = 0;
	/** @brief Revision incremented when atlas binding data changes. */
	uint32_t bindingRevision = 0;
};

/** @} */

} // namespace FlowUi::Font
